apiVersion: v1
kind: Service
metadata:
  name: zevrant-clamav-service
spec:
  ports:
    - port: 3310
      targetPort: 3310
  selector:
    app: zevrant-clamav-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-clamav-service-deployment
  labels:
    app: zevrant-clamav-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-clamav-service
  template:
    metadata:
      labels:
        app: zevrant-clamav-service
    spec:
      imagePullSecrets:
        - name: regcred

      containers:
        - name: zevrant-clamav-service
          image: mkodockx/docker-clamav
          env:
            - name: CLAMD_CONF_MaxFileSize
              value: 999999M
            - name: CLAMD_CONF_MaxScanSize
              value: 999999M
            - name: CLAMD_CONF_StreamMaxLength
              value: 999999M
          ports:
            - containerPort: 3310