apiVersion: v1
kind: Service
metadata:
  name: zevrant-keycloak-service
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30134
  selector:
    app: zevrant-keycloak-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-keycloak-service
  namespace: prod
  labels:
    app: zevrant-keycloak-service
spec:
  #  Additional config is needed to switch to HA mode
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-keycloak-service
  template:
    metadata:
      labels:
        app: zevrant-keycloak-service
    spec:
      imagePullSecrets:
        - name: regcred

      containers:
        - name: zevrant-keycloak-service
          image: harbor.zevrant-services.internal/zevrant-services/keycloak-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /auth
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /auth
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: zevrant-keycloak-service-db
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-password
                  key: password
            - name: DB_USER
              value: zevrant
            - name: SERVICE_NAME
              value: zevrant-keycloak-service
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENVIRONMENT
              value: prod
            - name: JDBC_PARAMS
              value: 'connectionTimeout=30000'
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: ADDITIONAL_IP
              value: '172.16.1.10'
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-vault-credentials
                  key: username
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: keycloak-vault-credentials
                  key: password
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
