apiVersion: v1
kind: Service
metadata:
  name: zevrant-home-ui
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30124
      name: app-port
    - port: 80
      targetPort: 80
      name: acme
  selector:
    app: zevrant-home-ui
#
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: ingress-nodeport-prod
#  namespace: prod
#spec:
#  type: NodePort
#  ports:
#    - port: 9090
#      targetPort: 9090
#      nodePort: 30122
#  selector:
#    app: zevrant-prometheus-service
