apiVersion: v1
kind: Service
metadata:
  name: zevrant-vault-service
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8200
      nodePort: 30135
  selector:
    app: zevrant-vault-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-vault-service
  namespace: prod
  annotations:
    iam.amazonaws.com/role: OauthServiceRole
  labels:
    app: zevrant-vault-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-vault-service
  template:
    metadata:
      labels:
        app: zevrant-vault-service
    spec:
      volumes:
        - name: password-volume
          emptyDir:
            sizeLimit: "1Mi"
        - name: vault-data
          nfs:
            server: nfs-controller.zevrant-services.com
            path: /nfs/exports/vault
        - name: vault-data2
          iscsi:
            iqn: iqn.2005-10.org.freenas.ctl:vault-develop
            lun: 0
            targetPortal: 172.16.1.8
        - name: vault-keys
          secret:
            secretName: vault-key
            defaultMode: 0400
      initContainers:
        - name: init-myservice
          image: harbor.zevrant-services.internal/zevrant-services/ubuntu-base:latest
          volumeMounts:
            - mountPath: /opt/secrets
              name: password-volume
            - mountPath: /var/zevrant-services/vault-keys
              name: vault-keys
          command:
            - |
              /bin/bash -c
              mkdir -p /opt/secrets/vault-keys
              cp /var/zevrant-services/vault-keys/* /opt/secrets/vault-keys/
              chown -R 1000:1000 /opt/secrets
      containers:
        - name: vault-unsealer
          image: harbor.zevrant-services.internal/zevrant-services/vault-unsealer:latest
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /var/zevrant-services
              name: password-volume
          env:
            - name: URL
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: zevrant-vault-service
          image: harbor.zevrant-services.internal/zevrant-services/vault:latest
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          imagePullPolicy: Always
          args:
            - server
          volumeMounts:
            - name: vault-data
              mountPath: /vault
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: zevrant-vault-service
            - name: CERTIFICATE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: certificate-credentials
                  key: username
            - name: CERTIFICATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: certificate-credentials
                  key: password
          ports:
            - containerPort: 8200
          resources:
            requests:
              memory: 8Gi
              cpu: 2000m
            limits:
              memory: 8Gi
              cpu: 2000m
