apiVersion: v1
kind: Service
metadata:
  name: certificate-authority
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: certificate-authority

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificate-authority
  namespace: monitoring
spec:
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "csi-rbd-sc"
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-authority
  namespace: monitoring
  labels:
    app: certificate-authority
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: certificate-authority
  template:
    metadata:
      labels:
        app: certificate-authority
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      imagePullSecrets:
        - name: regcred
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 172.16.1.2
      volumes:
        - name: step-ca
          persistentVolumeClaim:
            claimName: certificate-authority
        - name: ca-password
          secret:
            secretName: certificate-authority-password
      containers:
        - name: certificate-authority
          image: harbor.zevrant-services.internal/zevrant-services/step-ca:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: step-ca
              mountPath: /opt/step-ca
            - name: ca-password
              mountPath: /var/zevrant-services/ca-password
          env:
            - name: CA_NAME
              value: 'Zevrant Services Monitoring'
            - name: CA_DNS
              value: certificate-authority
            - name: SECRET_FILE_PATH
              value: /var/zevrant-services/ca-password/password
#          readinessProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /acme/acme/directory
#              port: 8443
#            failureThreshold: 5
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /acme/acme/directory
#              port: 8443
#            failureThreshold: 5
#            periodSeconds: 5