apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-monitoring
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: minio-monitoring.preprod.zevrant-services.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-console
                port:
                  name: https-console
    - host: api.minio-monitoring.preprod.zevrant-services.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: https-minio
  ingressClassName: nginx
  tls:
    - hosts:
      - minio-monitoring.preprod.zevrant-services.internal
      - api.minio-monitoring.preprod.zevrant-services.internal
      secretName: minio-monitoring-tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-monitoring
  namespace: monitoring
spec:
  secretName: minio-monitoring-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 13h
  dnsNames:
    - minio-monitoring.preprod.zevrant-services.internal
    - api.minio-monitoring.preprod.zevrant-services.internal

