apiVersion: v1
kind: Service
metadata:
  namespace: monitoring2
  name: minio-console
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30142
      name: http
    - port: 9433
      targetPort: 9433
      nodePort: 30143
      name: https
  selector:
    app: console