#apiVersion: kadalu-operator.storage/v1alpha1
#kind: KadaluStorage
#metadata:
#  name: monitoring
#  namespace: monitoring
#spec:
#  type: "Disperse"
#  storage:
#    - node: "zevrant-01"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#    - node: "zevrant-02"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#    - node: "zevrant-03"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#    - node: "zevrant-04"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#    - node: "zevrant-05"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#    - node: "zevrant-06"
#      path: "/glusterfs/bricks/kadalu/monitoring"
#  disperse:
#    data: 4
#    redundancy: 2
#  pvReclaimPolicy: delete
#
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: monitoring-ca
#  namespace: monitoring
#spec:
#  storageClassName: kadalu.monitoring
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  volumeName: "pvc-2f4a99e5-06e5-44e2-a058-c12ee305398d"
#
#---
#
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: grafana-database
#  namespace: monitoring
#spec:
#  storageClassName: kadalu.monitoring
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  volumeName: "pvc-03ac932f-0647-475b-9364-ab454eee179d"
#
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: loki-cache
#  labels:
#    app.kubernetes.io/name: loki-cache
#  namespace: monitoring
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: kadalu.monitoring
#  volumeMode: Filesystem
#
#
#
#
#
