apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-issuer
  namespace: preprod-shared
spec:
  acme:
    email: gdittrick@zevrant-services.com
    privateKeySecretRef:
      name: ca-private-key
      key: privateKey
    server: https://certificate-authority.preprod-shared.svc.cluster.local/acme/acme/directory
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIyekNDQVdJQ0ZFY0VQTkFyZXkwZFcwbTltMUFINGU2cUxXblRNQW9HQ0NxR1NNNDlCQU1FTUZJeEN6QUoKQmdOVkJBWVRBbFZUTVJFd0R3WURWUVFJREFoTmFXTm9hV2RoYmpFUk1BOEdBMVVFQnd3SVFtRjVJRU5wZEhreApIVEFiQmdOVkJBTU1GSHBsZG5KaGJuUXRjMlZ5ZG1salpYTXVZMjl0TUI0WERUSXlNRGd5TURFMk16WTFObG9YCkRUSXpNRGd5TURFMk16WTFObG93VWpFTE1Ba0dBMVVFQmhNQ1ZWTXhFVEFQQmdOVkJBZ01DRTFwWTJocFoyRnUKTVJFd0R3WURWUVFIREFoQ1lYa2dRMmwwZVRFZE1Cc0dBMVVFQXd3VWVtVjJjbUZ1ZEMxelpYSjJhV05sY3k1agpiMjB3ZGpBUUJnY3Foa2pPUFFJQkJnVXJnUVFBSWdOaUFBUyt1L2ZEOFF1SEdmQjJuRFhLeUNHYWRJMFpSSzFGCkVrU1U5bzVmYS94QXh1SGVkdmFjUDUyQk9ldERRRlUxa0JlVStoM0gxWVB0cHV6U0hGcnhkQWlkVXByQTVDYjEKVEV5N1FQdkdZMGhOZ05aNWVvSEVKd1lUZUs2MUlQL2I4ZzB3Q2dZSUtvWkl6ajBFQXdRRFp3QXdaQUl3UDdkegpsSmZiOEhQQW5NTklrKzJzUXh5bHRmMWJYUXJUeDY3R1Q1dlllMlZTNzV5STYyWlYveWNHUmdTbTlkSmRBakJBCk1nM21rTlc0djRNeldZMmZFcnRta1RSdVZ1NW4vc2FDSnBHWi82akFLMHFSdHpBQWRETkpsUHRWMk5QWE1WRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    solvers:
      - selector:
          dnsZones:
            - 'preprod.zevrant-services.com'
        dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIA2RW3K76J3UBZ3SYO
            hostedZoneID: Z0811917POV9YNOM5LQ5
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key