apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
spec:
  secretName: authentik-public-tls
  issuerRef:
    name: lets-encrypt
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h #90d
  renewBefore: 1440h # 60d
  dnsNames:
    - auth.preprod.zevrant-services.com

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-internal
spec:
  secretName: authentik-internal-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 14h
  dnsNames:
    - auth.preprod.zevrant-services.internal