apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: preprod-shared
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30133
      name: https
    - port: 80
      targetPort: 80
      nodePort: 30137
      name: http
  selector:
    app: keycloak
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: preprod-shared
spec:
  secretName: keycloak-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always
  duration: 24h
  renewBefore: 13h
  dnsNames:
    - keycloak.preprod.zevrant-services.com
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: preprod-shared
  labels:
    app: keycloak
spec:
  #  Additional config is needed to switch to HA mode
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      volumes:
        - name: keycloak-cert
          secret:
            secretName: keycloak-tls
      imagePullSecrets:
        - name: regcred
      containers:
        - name: keycloak
          image: docker.io/zevrant/keycloak:18.0.2
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
            - /opt/keycloak/bin/kc.sh start
          volumeMounts:
            - name: keycloak-cert
              mountPath: /opt/acme/certs/
          ports:
            - containerPort: 8443
          startupProbe:
            httpGet:
              scheme: HTTPS
              path: /health/ready
              port: 8443
            periodSeconds: 5
            failureThreshold: 16 #max of 80 seconds
            successThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/live
              port: 8443
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: KC_DB_URL_HOST
              value: keycloak-db
            - name: KC_DB_URL_PORT
              value: '5432'
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-password
                  key: password
            - name: KC_DB_USERNAME
              value: zevrant
#            - name: KC_DB_URL_PROPERTIES
#              value: 'connectionTimeout=30000'
            - name: KC_PROXY
              value: "passthrough"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
            - name: KEYCLOAK_STATISTICS
              value: ''
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /opt/acme/certs/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /opt/acme/certs/tls.key
            - name: KC_HOSTNAME
              value: keycloak.preprod.zevrant-services.com
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: 'true'
            - name: KC_HTTP_ENABLED
              value: 'false'
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
