apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: preprod-shared
spec:
  secretName: vault-tls
  issuerRef:
    name: acme-issuer
  duration: 24h
  renewBefore: 23h
  dnsNames:
    - test.preprod.zevrant-services.com