apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: develop
spec:
  ports:
    - port: 3310
      targetPort: 3310
      name: clamav
  selector:
    app: clamav

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  labels:
    app: clamav
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      imagePullSecrets:
        - name: harbor-ro
      containers:
        - name: clamav
          image: harbor.zevrant-services.com/dockerhub/clamav/clamav:latest
          env:
            - name: CLAMD_CONF_MaxFileSize
              value: 999999M
            - name: CLAMD_CONF_MaxScanSize
              value: 999999M
            - name: CLAMD_CONF_StreamMaxLength
              value: 999999M
          ports:
            - containerPort: 3310