#apiVersion: v1
#kind: Service
#metadata:
#  name: zevrant-kafka-zookeeper-ui-service
#  namespace: develop
#spec:
#  type: NodePort
#  ports:
#    - port: 9000
#      targetPort: 9000
#      nodePort: 30122
#  selector:
#    app: zevrant-kafka-zookeeper-service
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: zevrant-kafka-zookeeper-service
#spec:
#  ports:
#    - port: 443
#      targetPort: 2181
#  selector:
#    app: zevrant-kafka-zookeeper-service
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: zevrant-kafka-service
#spec:
#  ports:
#    - port: 443
#      targetPort: 9092
#  selector:
#    app: zevrant-kafka-service
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zevrant-kafka-zookeeper-service-deployment
#  labels:
#    app: zevrant-kafka-zookeeper-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: zevrant-kafka-zookeeper-service
#  template:
#    metadata:
#      labels:
#        app: zevrant-kafka-zookeeper-service
#    spec:
#      imagePullSecrets:
#        - name: harbor-ro
#      containers:
#        - name: zevrant-kafka-zookeeper-service
#          image: bitnami/zookeeper:3.7.0
#          env:
#            - name: ALLOW_ANONYMOUS_LOGIN
#              value: "yes"
#          ports:
#            - containerPort: 2181
#        - name: zevrant-kafka-zookeper-ui-service
#          image: elkozmon/zoonavigator:1.1.0
#          ports:
#            - containerPort: 9000
#---
#apiVersion: apps/v1
#kind: DaemonSet
#metadata:
#  name: zevrant-kafka-service-daemonset
#  labels:
#    app: zevrant-kafka-service
#spec:
#  selector:
#    matchLabels:
#      app: zevrant-kafka-service
#  template:
#    metadata:
#      labels:
#        app: zevrant-kafka-service
#    spec:
#      volumes:
#        - name: kafka-storage
#          hostPath:
#            path: /opt/kafka/dev/
#      imagePullSecrets:
#        - name: harbor-ro
#      containers:
#        - name: zevrant-kafka-broker-service
#          image: bitnami/kafka:2.8.0
#          volumeMounts:
#            - name: kafka-storage
#              mountPath: /bitnami/kafka
#          ports:
#            - containerPort: 9092
#          env:
#            - name: ALLOW_PLAINTEXT_LISTENER
#              value: "yes"
#            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#              value: "zevrant-kafka-zookeeper-service:443"
