apiVersion: v1
kind: Service
metadata:
  name: zevrant-home-ui
  namespace: develop
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30124
      name: app-port
    - port: 80
      targetPort: 80
      nodePort: 30119
      name: acme
  selector:
    app: zevrant-home-ui
