apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:

  containers:
    - args:
        - -c
        - sleep infinity
      command:
        - /bin/bash
      image: docker.io/ubuntu:latest
      imagePullPolicy: Always
      name: test-pod
