apiVersion: v1
data:
  fingerprint: YWQwYTY2MjEzZWU5N2Y5MjNjODY2MDNiYzc2Y2EzMWFhM2JhNjZkYWU1MTI0ZTAyOGU1YWNjZjQ0ZWM3MTRmMQo=
kind: Secret
metadata:
  name: ca-fingerprint
  namespace: preprod-shared
type: Opaque