apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-certificates
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "update"
      - "create"
      - "patch"
