apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: createAutoscaling
rules:
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - "create"
      - "patch"
