apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-metrics
rules:
  - nonResourceURLs:
    - /apis/metrics.k8s.io/*
    - /api/v1/nodes/*
    - /metrics*
    - /metrics/cadvisor*
    - /metrics/cadvisor/*
    verbs:
      - get
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - services
      - nodes
      - metrics
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - "storage.k8s.io"
      - "certificates.k8s.io"
      - "policy"
      - "ingresses.networking.k8s.io"
      - "apps"
      - "storage.k8s.io"
      - "autoscaling"
      - "admissionregistration.k8s.io"
      - "networking.k8s.io"
      - "coordination.k8s.io"
      - "batch"
    resources:
      - nodes/metrics
      - nodes/stats
      - metrics
      - configmaps
      - secrets
      - nodes
      - pods
      - services
      - statefulsets
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
      - storageclasses
      - certificatesigningrequests
      - poddisruptionbudgets
      - ingresses
      - leases
      - replicasets
      - horizontalpodautoscalers
      - validatingwebhookconfigurations
      - volumeattachments
      - mutatingwebhookconfigurations
      - networkpolicies
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
