apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readOnly
rules:
  - apiGroups: [ "", "apps", "autoscaling" ] # "" indicates the core API group
    resources: [ "*"]
    verbs: [ "get", "watch", "list" ]
