apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-secrets
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "secrets" ]
    verbs:
      - get
      - patch
      - create
      - list
      - watch