apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "ced1a5f3-dd0d-4761-9d7a-dd8fca262ba5",
        "monitors": [
          "172.16.1.8:6789",
          "172.16.1.5:6789",
          "172.16.1.7:6789",
          "172.16.1.4:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph

---

apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {}
metadata:
  name: ceph-csi-encryption-kms-config
  namespace: ceph

---

apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  # keyring is a required key and its value should be empty
  keyring: |
metadata:
  name: ceph-config
  namespace: ceph