apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "86137ef7-01fe-451a-aac5-d1d469af8126",
        "monitors": [
          "172.16.1.3:6789",
          "172.16.1.16:6789",
          "172.16.1.21:6789",
          "172.16.1.23:6789",
          "172.16.1.58:6789",
          "172.16.1.57:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi


---

apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {}
metadata:
  name: ceph-csi-encryption-kms-config
  namespace: ceph-csi

---

apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  # keyring is a required key and its value should be empty
  keyring: |
metadata:
  name: ceph-config
  namespace: ceph-csi