---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-postgres
  namespace: preprod-shared
spec:
  secretName: keycloak-postgres-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 11h
  dnsNames:
    - keycloak-postgres.preprod.zevrant-services.com