apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: preprod-shared
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: keycloak

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-public
spec:
  secretName: keycloak-public-tls
  issuerRef:
    name: lets-encrypt
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h #90d
  renewBefore: 1440h # 60d
  dnsNames:
    - auth.preprod.zevrant-services.com


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: preprod-shared
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: auth.preprod.zevrant-services.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: https
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-public
  namespace: preprod-shared
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
    - host: auth.preprod.zevrant-services.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: https
  ingressClassName: nginx
  tls:
    - secretName: keycloak-public-tls
      hosts:
        - auth.preprod.zevrant-services.com

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: preprod-shared
spec:
  secretName: keycloak-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always
  duration: 24h
  renewBefore: 13h
  dnsNames:
    - auth.preprod.zevrant-services.internal
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: preprod-shared
  labels:
    app: keycloak
spec:
  #  Additional config is needed to switch to HA mode
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      volumes:
        - name: keycloak-cert
          secret:
            secretName: keycloak-tls
      imagePullSecrets:
        - name: harbor-ro
      containers:
        - name: keycloak
          image: harbor.zevrant-services.internal/quay/keycloak/keycloak:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
#            - sleep infinity
            - /opt/keycloak/bin/kc.sh start
          volumeMounts:
            - name: keycloak-cert
              mountPath: /opt/acme/certs/
          ports:
            - containerPort: 8443
#          startupProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /health/ready
#              port: 8443
#            periodSeconds: 5
#            failureThreshold: 32 #max of 160 seconds
#            successThreshold: 1
#          livenessProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /health/live
#              port: 8443
#            periodSeconds: 5
#            failureThreshold: 3
#            successThreshold: 1
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: keycloak-db-pguser-keycloak
            - name: KC_DB_URL_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: keycloak-db-pguser-keycloak
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: keycloak-db-pguser-keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-pguser-keycloak
                  key: password
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: keycloak-db-pguser-keycloak
            - name: KC_DB_SCHEMA
              value: public
#            - name: KC_DB_URL_PROPERTIES
#              value: 'connectionTimeout=30000&useSSL=false&allowPublicKeyRetrieval=true'
            - name: KC_PROXY
              value: "passthrough"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
            - name: KEYCLOAK_STATISTICS
              value: ''
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /opt/acme/certs/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /opt/acme/certs/tls.key
            - name: KC_HOSTNAME_URL
              value: https://auth.preprod.zevrant-services.internal
            - name: KC_TRANSACTION_XA_ENABLED
              value: 'true'
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: 'true'
            - name: KC_HTTP_ENABLED
              value: 'false'
            - name: KC_LOG_LEVEL
              value: debug
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'




