---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-postgres
  namespace: shared
spec:
  secretName: gitea-postgres-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 2000h
  dnsNames:
    - gitea-postgres.zevrant-services.com