name: "gitea-redis"
imagePullSecrets:
  - "regcred"
storageClassName: "csi-rbd-sc"
storageSize: 1Gi
storageSizeLimit: 1Ti
replicas: 2
redisMasterPasswordSecret: "gitea-redis-credentials"
quorumCount: 1
failoverTimeout: 10000
downAfterMillis: 5000
sentinelReplicas: 3
sentinelImage: docker.io/zevrant/redis-sentinel:latest
redisImage: docker.io/redis:7.2-rc3
additionalUsers:
  - username: gitea
    passwordSecret: gitea-redis-password
    passwordSecretKey: "" #default is password i.e. --from-literal password='some password here'
    permissions: [] #i.e +@all -@connect, etc
