apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
spec:
  secretName: harbor-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 2000h
  dnsNames:
    - harbor.zevrant-services.com

---

#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: harbor
#spec:
#  secretName: harbor-tls
#  issuerRef:
#    name: acme-issuer
#  privateKey:
#    algorithm: ECDSA
#    size: 256
#    rotationPolicy: Always
#  duration: 2160h
#  renewBefore: 2000h
#  dnsNames:
#    - harbor.zevrant-services.com