apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
spec:
  secretName: jenkins-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h #90d
  renewBefore: 1440h # 60d
  dnsNames:
    - jenkins.zevrant-services.com
