apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
spec:
  secretName: jenkins-tls
  issuerRef:
    name: lets-encrypt
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h #90d
  renewBefore: 1440h # 60d
  dnsNames:
    - jenkins.zevrant-services.com

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-internal
spec:
  secretName: jenkins-internal-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 23h
  commonName: jenkins.zevrant-services.internal
  dnsNames:
    - jenkins.zevrant-services.internal
