apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: agent-port
    - port: 8443
      targetPort: 8443
      name: https
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: jenkins

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: jenkins
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-public
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
    - host: jenkins.zevrant-services.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  name: https
  ingressClassName: nginx
  tls:
    - secretName: jenkins-tls
      hosts:
        - jenkins.zevrant-services.com
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: jenkins.zevrant-services.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  name: https
  ingressClassName: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 1.1.1.1
      serviceAccountName: jenkins
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-data
        - name: password-volume
          emptyDir:
            sizeLimit: "1Mi"
        - name: keystore-volume
          emptyDir:
            sizeLimit: "1Mi"
        - name: jenkins-cert
          secret:
            secretName: jenkins-internal-tls
            defaultMode: 0400
      imagePullSecrets:
        - name: harbor-ro
      initContainers:
        - name: secret-init
          image: harbor.zevrant-services.internal/zevrant-services/ubuntu-base:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /opt/secrets
              name: password-volume
              readOnly: false
            - mountPath: /opt/keystore
              name: keystore-volume
              readOnly: false
            - name: jenkins-cert
              mountPath: /opt/acme/certs
              readOnly: true
          command:
            - /bin/bash
          args:
            - -c
            - |
              mkdir -p /opt/secrets/keystore
              openssl rand 256 | base64 -w 0 > /opt/secrets/password
              openssl pkcs12 -export -inkey /opt/acme/certs/..data/tls.key -in /opt/acme/certs/..data/tls.crt -passout 'file:/opt/secrets/password' -out /opt/keystore/zevrant-services.p12
      containers:
        - name: jenkins
          image: harbor.zevrant-services.internal/zevrant-services/jenkins:lts-jdk17
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
            - |
              mkdir -p /var/jenkins_home/casc_configs
              export JENKINS_OPTS="$JENKINS_OPTS --httpsKeyStorePassword=$(cat /var/zevrant-services/keystore/password)"
              git config --global --add safe.directory /var/jenkins_home/workspace/*
              /usr/local/bin/jenkins.sh
          startupProbe:
            httpGet:
              scheme: HTTPS
              path: /login
              port: 8443
            periodSeconds: 5
            failureThreshold: 80
            successThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /login
              port: 8443
            periodSeconds: 15
            failureThreshold: 2
            successThreshold: 1
          volumeMounts:
            - mountPath: /var/jenkins_home/
              name: jenkins
            - mountPath: /var/zevrant-services/keystore
              name: password-volume
            - mountPath: /opt/acme/certs/
              name: keystore-volume
          ports:
            - containerPort: 8443
              name: https-port
            - containerPort: 5000
              name: agent-port
          resources:
            requests:
              memory: 8Gi
              cpu: 4000m
            limits:
              memory: 8Gi
              cpu: 4000m
          env:
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/casc_configs/"
            - name: JENKINS_OPTS
              value: "--httpPort=8080 --httpsPort=8443 --httpsKeyStore=/opt/acme/certs/zevrant-services.p12 -Djavax.net.ssl.trustStore=/var/jenkins_home/keystore/cacerts"
            - name: JAVA_OPTS
              value: >
                -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
            - name: JENKINS_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: JENKINS_HTTPS_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: JENKINS_HTTPS_PORT
              value: "8443"
            - name: JENKINS_HTTPS_KEYSTORE
              value: "/opt/acme/certs/zevrant-services.p12"



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-clone
  namespace: jenkins
  labels:
    app: jenkins-clone
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins-clone
  template:
    metadata:
      labels:
        app: jenkins-clone
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      volumes:
        - name: jenkins-clone
          persistentVolumeClaim:
            claimName: clone-of-pvc-1
      imagePullSecrets:
        - name: harbor-ro
      containers:
        - name: jenkins
          image: harbor.zevrant-services.internal/zevrant-services/jenkins:lts-jdk17
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
            - |
              sleep 9999999999
          volumeMounts:
            - mountPath: /var/jenkins_home/
              name: jenkins-clone