apiVersion: batch/v1
kind: CronJob
metadata:
  name: jenkins-restart
spec:
  schedule: "1 3 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jenkins-restart
          imagePullSecrets:
            - name: regcred
          containers:
            - name: kubectl
              image: docker.io/zevrant/kubectl:latest
              imagePullPolicy: Always
              command:
                - /bin/bash
              args:
                - -c
                - |
                  kubectl rollout restart deploy jenkins
                  kubectl rollout status deploy jenkins --timeout=5m
                  code="$?"
                  status="SUCESS"
                  color="2026501"
                  if [[ code -gt 0 ]]; then
                    status="FAILURE"
                    color="14625579" 
                  fi
                  
                  jsonBody='{"embeds": [{"title": "Jenkins Instance Certificate Rotation", "description": "'
                  jsonBody+="$status"
                  jsonBody+='", "color": '
                  jsonBody+="$color"
                  jsonBody+='}]}'
                  curl \
                    -H "Content-Type: application/json" \
                    -d  "$jsonBody" \
                    https://discord.com/api/webhooks/957798877954715719/worHVe7qTwykMPmL-_C7iKV7OMDHenx7dhUckkQL24hcdqsSRaOKIR_9gRqJymZx5qgP
          restartPolicy: OnFailure