apiVersion: v1
kind: Service
metadata:
  name: keydb-loadbalancer
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: jenkins-versions-database
    app.kubernetes.io/name: keydb
  ports:
    - name: server
      nodePort: 31968
      port: 6379
      targetPort: 6379
      protocol: TCP