apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-restart-create-deployments-jenkins
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins-restart # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-restart-read-only
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins-restart # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io