apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: monitoring-read-only
  namespace: monitoring
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only-preprod-shared
  namespace: preprod-shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only-shared
  namespace: shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only-develop
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jenkins-read-only-prod
  namespace: prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: readOnly # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-pods
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-exec-pods-shared
  namespace: shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: execPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-services-develop
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createServices # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-services-prod
  namespace: prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createServices # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-preprod-shared
  namespace: preprod-shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-monitoring
  namespace: monitoring
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-jenkins
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-shared
  namespace: shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-develop
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-deployments-prod
  namespace: prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createDeployments # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-exec-pods
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: execPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-exec-pods-monitoring
  namespace: monitoring
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: execPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-exec-pods-develop
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: execPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-exec-pods-preprod-shared
  namespace: preprod-shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: execPods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-secrets-develop
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-secrets-preprod-shared
  namespace: preprod-shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-secrets-jenkins
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-create-secrets
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: cert-manager # "name" is case-sensitive
    namespace: cert-manager
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-secrets-monitoring
  namespace: monitoring
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-certificates
  namespace: develop
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-certificates # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-secrets-shared
  namespace: shared
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: create-secrets # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-delete-pods
  namespace: jenkins
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: deletePods # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-autoscaling-prod
  namespace: prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createAutoscaling # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-pvc-prod
  namespace: prod
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jenkins # "name" is case-sensitive
    namespace: jenkins
    apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: createPvc # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io



---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-develop-permissions
  namespace: develop
rules:
  - apiGroups:
      - ""
      - "apps"
      - "autoscaling"
      - "postgres-operator.crunchydata.com"
    resources:
      - deployments
      - services
      - secrets
      - replicasets
      - persistentvolumeclaims
      - horizontalpodautoscalers
      - postgresclusters
    verbs:
      - create
      - get
      - patch
      - list
      - update
      - delete
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-develop-permissions
  namespace: develop
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
    apiGroup: ""
roleRef:
  kind: Role
  name: jenkins-develop-permissions
  apiGroup: rbac.authorization.k8s.io

