#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  finalizers:
#    - kubernetes.io/pvc-protection
#  labels:
#    v1.min.io/log-pg: shared-log
#  name: shared-log-shared-log-0
#  namespace: shared
#spec:
#  storageClassName: csi-rbd-sc
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi
#  volumeMode: Filesystem
