---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  secretName: grafana-postgres-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 2000h
  dnsNames:
    - grafana-postgres.preprod.zevrant-services.com