apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/console: loki-console
      v1.min.io/pool: pool-0
      v1.min.io/tenant: loki
    name: data0-loki-pool-0-0
    namespace: monitoring
  spec:
    storageClassName: kadalu.monitoring
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "274877906944"
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-d3d2b46f-93ac-4b3a-bc51-219cbfea7e9b
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 256Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/console: loki-console
      v1.min.io/pool: pool-0
      v1.min.io/tenant: loki
    name: data0-loki-pool-0-1
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "274877906944"
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-89a68419-d233-4f74-ac6f-8d58c4de478f
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    creationTimestamp: "2023-02-02T20:03:19Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/console: loki-console
      v1.min.io/pool: pool-0
      v1.min.io/tenant: loki
    name: data0-loki-pool-0-2
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "274877906944"
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-01c5d7dd-6058-4e82-ba00-10b649c6c7aa
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/console: loki-console
      v1.min.io/pool: pool-0
      v1.min.io/tenant: loki
    name: data0-loki-pool-0-3
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "274877906944"
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-57e159bc-9995-47ff-a6f7-33771473ce42
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"grafana-database","namespace":"monitoring"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"kadalu.monitoring"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    name: grafana-database
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-03ac932f-0647-475b-9364-ab454eee179d
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"v1.min.io/log-pg":"loki-log"},"name":"loki-log-loki-log-0","namespace":"monitoring"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5368709120"}},"storageClassName":"kadalu.monitoring","volumeMode":"Filesystem"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/log-pg: loki-log
    name: loki-log-loki-log-0
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "5368709120"
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-8f6fbbcf-5720-4927-829e-6deb78a5d2e0
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      v1.min.io/prometheus: loki-prometheus
    name: loki-prometheus-loki-prometheus-0
    namespace: monitoring
  spec:
    storageClassName: kadalu.monitoring
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"metrics-database","namespace":"monitoring"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"kadalu.monitoring"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    name: metrics-database
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-430015b1-ced8-4bb5-ae07-531b4696f39b
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"monitoring-ca","namespace":"monitoring"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"kadalu.monitoring"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kadalu
      volume.kubernetes.io/storage-provisioner: kadalu
    finalizers:
    - kubernetes.io/pvc-protection
    name: monitoring-ca
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kadalu.monitoring
    volumeMode: Filesystem
    volumeName: pvc-2f4a99e5-06e5-44e2-a058-c12ee305398d
kind: List
metadata:
  resourceVersion: ""
