apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog-receiver
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 1514
      targetPort: 1514
      nodePort: 30123
      name: syslog-receiver
      protocol: TCP
  selector:
    app: promtail

---

apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
spec:
  ports:
    - port: 9080
      targetPort: 9080
      name: http
  selector:
    app: promtail

---

apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: promtail
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30620
      name: http
  selector:
    app: promtail


#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: promtail
#  namespace: monitoring
#spec:
#  secretName: promtail-tls
#  issuerRef:
#    name: acme-issuer
#  duration: 24h
#  renewBefore: 23h
#  dnsNames:
#    - promtail.preprod.zevrant-services.com
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      volumes:
        #        - name: promtail-cert
        #          secret:
        #            secretName: promtail-tls
        - name: promtail-config
          configMap:
            name: promtail
        - name: host-logs
          hostPath:
            path: /var/log
      imagePullSecrets:
        - name: regcred
      containers:
        - name: promtail
          image: grafana/promtail:latest
          imagePullPolicy: Always
          args:
            - -config.file=/mnt/config/config.yml
          volumeMounts:
            #            - name: promtail-cert
            #              mountPath: /opt/acme/certs/
            - name: host-logs
              mountPath: /opt/host
            - name: promtail-config
              mountPath: /mnt/config
          ports:
            - containerPort: 9080
              name: promtail-alert
              protocol: TCP
            - containerPort: 1514
              name: syslog-receiver
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /targets
              port: 9080
            periodSeconds: 5
            failureThreshold: 4
            successThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /targets
              port: 9080
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 4Gi
              cpu: 1000m

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: monitoring
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 9081
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki-write:3100/loki/api/v1/push
        tenant_id: "zevrant-services"
    
    scrape_configs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          listen_protocol: tcp
          idle_timeout: 60s
          label_structured_data: yes
          labels:
            job: "syslog"
        relabel_configs:
          - source_labels: ['__syslog_message_hostname']
            target_label: 'host'
      - job_name: node-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /opt/host/syslog
      - job_name: kubernetes_pods
        kubernetes_sd_configs:
            - role: pod
        pipeline_stages:
          - docker: { }
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            target_label: __service__
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: __host__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            source_labels:
              - name
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /opt/host/pods/*$1*/$2*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__

        
              
        
        
