apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: node-exporter
  labels:
    app: prometheus
spec:
  endpoints:
    - port: node-exporter
      scheme: http
      path: /metrics
      honorLabels: true
  jobLabel: node-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: node-exporter