apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artifactory
spec:
  secretName: artifactory-tls
  issuerRef:
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 13h
  dnsNames:
    - artifactory.zevrant-services.com

---

kind: PersistentVolumeClaim #TODO: use vault instead
apiVersion: v1
metadata:
  name: artifactory-key
  namespace: shared
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: shared
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30127
      name: http
    - port: 8082
      targetPort: 8082
      nodePort: 30123
      name: ui
  selector:
    app: artifactory

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artifactory
  namespace: shared
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      securityContext:
        fsGroup: 1030
        fsGroupChangePolicy: "Always"
      imagePullSecrets:
        - name: regcred
      volumes:
#        - name: keystore-volume
#          emptyDir:
#            sizeLimit: "1Mi"
#            defaultMode: 0400
        - name: artifactory-config
          configMap:
            name: artifactory
        - name: artifactory-keys
          persistentVolumeClaim:
            claimName: artifactory-keys
      initContainers:
        - name: config-init
          imagePullPolicy: Always
          image: docker.io/zevrant/ubuntu-base:latest
          volumeMounts:
#            - name: artifactory-keys
#              mountPath: /var/opt/jfrog/artifactory/etc/
            - mountPath: /var/config/artifactory-config
              name: artifactory-config
          command:
            - /bin/sh
          args:
            - -c
            - ls -l /var/config/artifactory-config/
            - cp /var/config/artifactory-config/system.yaml /var/opt/jfrog/artifactory/etc/system.yaml
            - cp /var/config/artifactory-config/binarystore.xml /var/opt/jfrog/artifactory/etc/artifactory/binarystore.xml
      containers:
        - name: artifactory
          image: releases-docker.jfrog.io/jfrog/artifactory-jcr:latest
          #          command:
          #            - /bin/sh
          #          args:
          #            - -c
          #            - sleep 9999999999
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 2222
          volumeMounts:
#            - name: artifactory-cert
#              mountPath: /opt/acme/certs
#              readOnly: true
#            - name: artifactory-keys
#              mountPath: /var/opt/jfrog/artifactory/etc/
#            - name: artifactory-key
#              mountPath: /var/opt/jfrog/artifactory/etc/security/
          env:
            - name: JF_SHARED_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: artifactory-db-password
            - name: JF_SHARED_DATABASE_USERNAME
              value: zevrant
            - name: JFROG_HOME
              value: /var/opt/jfrog
#            - name: HA_HOST_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP
#          startupProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /api/healthz
#              port: 3000
#            failureThreshold: 14
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              scheme: HTTPS
#              path: /api/healthz
#              port: 3000
#            failureThreshold: 5
#            periodSeconds: 5


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory
  namespace: shared
data:
  system.yaml: |
    configVersion: 1
    shared:
      #security:
        #joinKeyFile: /var/opt/jfrog/artifactory/etc/security/join.key
        #masterKeyFile: /var/opt/jfrog/artifactory/etc/security/master.key
      node:
        haEnabled: false
      database:
        type: postgresql
        driver: org.postgresql.Driver
        url: jdbc:postgresql://artifactory-db:5432/artifactory
      metrics:
        enabled: true
      healthCheck:
        intervalSecs: 15
        probes:
          readiness:
            failOnLongFailingReadiness:
              enabled: true
            failureDurationSecs: 60
          liveness:
            failOnLongFailingReadiness:
              enabled: true
            failureDurationSecs: 60
#  binarystore.xml:
#    <config version="2">
#      <chain>
#        <provider id="cache-fs" type="cache-fs">
#          <provider id="s3-storage-v3" type="s3-storage-v3"/>
#          </provider>
#      </chain>
#      <provider id="s3-storage-v3" type="s3-storage-v3">
#        <endpoint>https://minio.shared.svc.cluster.local/</endpoint>
#        <bucketName>artifactory</bucketName>
#        <path></path>
#        <region>us-east-1</region>
#        <identity>artifactory</identity>
#        <credential>a&oV5s9HmR^VS2D#3gc#*%Q3dSZhs7^!9urv5Ckr</credential>
#      </provider>
#    </config>