apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
automountServiceAccountToken: true
imagePullSecrets:
  - name: regcred

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jenkins
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - "pods/exec"
    verbs:
      - "get"
      - "create"
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - "pods"
      - "secrets"
    verbs:
      - "delete"
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "create"
      - "patch"
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "update"
      - "create"
      - "patch"
  - apiGroups:
      - ""
      - apps
      - "networking.k8s.io"
    resources:
      - configmaps
      - secrets
      - nodes
      - pods
      - services
      - persistentvolumeclaims
      - persistentvolumes
      - deployments
      - replicasets
      - statefulsets
      - ingresses
    verbs:
      - get
      - patch
      - create
      - update
      - delete
      - list
      - watch
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-restart
  namespace: jenkins
automountServiceAccountToken: true
imagePullSecrets:
  - name: regcred
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-restart-secret
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-restart
type: kubernetes.io/service-account-token


