apiVersion: v1
data:
  Corefile: |
    .:53
    {
      errors
      health {
        lameduck 5s
      }
      ready
      log . {
          class error
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      prometheus :9153
      forward . 172.16.1.2
      cache 30
      loop
      reload
      loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
