---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanos
  namespace: monitoring
spec:
  secretName: thanos-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 23h
  dnsNames:
    - thanos.preprod.zevrant-services.internal

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 23h
  dnsNames:
    - prometheus.zevrant-services.internal