apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-operator
  namespace: minio-operator
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
    - host: minio-operator.zevrant-services.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  name: https
  ingressClassName: nginx
  tls:
    - hosts:
        - minio-operator.zevrant-services.internal
      secretName: minio-operator-tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-shared
  namespace: minio-operator
spec:
  secretName: minio-operator-tls
  issuerRef:
    name: step-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 24h
  renewBefore: 13h
  dnsNames:
    - minio-operator.zevrant-services.internal