apiVersion: v1
kind: Service
metadata:
  namespace: minio-operator
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30140
      name: http
    - port: 9433
      targetPort: 9433
      nodePort: 30141
      name: https
  selector:
    app: console