##Run as root user
- name: Install Proxmox Ansible Dependencies
  hosts: all
  remote_user: root
  tasks:
    - name: update cache and install python3-pip
      ansible.builtin.apt:
        pkg:
          - python3-pip
          - python3
          - python3-full
          - python3-proxmoxer
          - python3-requests
        update_cache: false
        state: latest
    - name: create non root user
      ansible.builtin.shell: |
        useradd -m zevrant -u 100001
        echo 'zevrant ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/no-password-root
        echo '\n' >> /etc/sudoers.d/no-password-root
        chmod 0440 /etc/sudoers.d/no-password-root
        mkdir /home/zevrant/.ssh/
        echo 'ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBLtOxtriPtNmisKkmfHfCByaTYCHRsDHyzQAi0yL6LUeKybjYExfR6N0xBMcIj6M/b5U3aafjKayX4nMvV7s7/vcrpBfW+WvxOCBWTlhKGNpUmAS9ApFDn51/FTuRgB/YA== Public key for PIV Authentication' > /home/zevrant/.ssh/authorized_keys
        echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEbQRaQyJ6MkFIW9y9ZfK0ukCpQoO5JNuCAw4PMxVFAn zevrant@zevrant' >> /home/zevrant/.ssh/authorized_keys
        chown -R zevrant:zevrant /home/zevrant/.ssh
        sed -i 's~zevrant:x:100001:10001::/home/zevrant:/bin/sh~zevrant:x:100001:10001::/home/zevrant:/bin/bash~g' /etc/passwd
        systemctl restart sshd
