- name: Setup Kubernetes On Host
  hosts: all
  become: true
  become_user: root
  serial: 1
  gather_facts: false
  tasks:
#    - name: Cordon K8S Node
#      become: false
#      local_action: ansible.builtin.command /snap/bin/kubectl cordon "{{ hostname }}"
#    - name: Drain K8S Node
#      become: false
#      local_action: ansible.builtin.command /snap/bin/kubectl drain "{{ hostname }}" --ignore-daemonsets --delete-emptydir-data
#    - name: Update Packages
#      ansible.builtin.yum:
#        use_backend: yum4
#        update_cache: true
#        name: '*'
#        state: latest
    - name: Copy Root Certificate
      ansible.builtin.copy:
        dest: /etc/pki/ca-trust/source/anchors/zevrant-services.crt
        content: |
          -----BEGIN CERTIFICATE-----
          MIICDTCCAbOgAwIBAgIUcfMqgTUkiJGW1NI6WAdQ815DyGQwCgYIKoZIzj0EAwIw
          VzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE1pY2hpZ2FuMREwDwYDVQQHDAhCYXkg
          Q2l0eTEiMCAGA1UEAwwZemV2cmFudC1zZXJ2aWNlcy5pbnRlcm5hbDAeFw0yMzA4
          MjExODQxNTdaFw0zMzA4MTgxODQxNTdaMFcxCzAJBgNVBAYTAlVTMREwDwYDVQQI
          DAhNaWNoaWdhbjERMA8GA1UEBwwIQmF5IENpdHkxIjAgBgNVBAMMGXpldnJhbnQt
          c2VydmljZXMuaW50ZXJuYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARRvcYB
          Qlv7B+Vr5FDOHbg9BXvl7pWrkZUGxwAsOEawl4YzD/3KvOAxF8RdYnO4bSRJuU7B
          tfzbk81bnQyKDFfio10wWzAdBgNVHQ4EFgQUEpenVXHlbvZcDAtH6c/OjFieUC0w
          HwYDVR0jBBgwFoAUEpenVXHlbvZcDAtH6c/OjFieUC0wDAYDVR0TBAUwAwEB/zAL
          BgNVHQ8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIgPdHcPE/tfknCePZFNUDkL/qQ
          O1bk9g6pqOxM3bTl5HMCIQDusvA6XLr23DUCljwV8kGKLOVhwpVA9A8CAw2WbBc/
          1A==
          -----END CERTIFICATE-----
    - name: Load Certificate
      ansible.builtin.command:
        cmd: update-ca-trust extract && openssl verify /etc/pki/ca-trust/source/anchors/zevrant-services.crt
#    - name: Reboot Node
#      ansible.builtin.reboot:
#        test_command: whoami
    - name: Uncordon K8S Node
      become: false
      local_action: ansible.builtin.command /snap/bin/kubectl uncordon "{{ hostname }}"