- name: Setup Kubernetes On Host
  hosts: all
  become: true
  become_user: root
  serial: 1
  gather_facts: false
  tasks:
    - name: Cordon K8S Node
      become: false
      local_action: ansible.builtin.command /snap/bin/kubectl cordon "{{ hostname }}"
      register: cordonresult
      until: "cordonresult is not failed"
      retries: 10
      delay: 10
    - name: Drain K8S Node
      become: false
      local_action: ansible.builtin.command /snap/bin/kubectl drain "{{ hostname }}" --ignore-daemonsets --delete-emptydir-data
      register: cordonresult
      until: "cordonresult is not failed"
      retries: 10
      delay: 10
    - name: Update Packages
      ansible.builtin.yum:
        use_backend: yum4
        update_cache: true
        name: '*'
        state: latest
    - name: Copy Root Certificate
      ansible.builtin.copy:
        dest: /etc/pki/ca-trust/source/anchors/zevrant-services.crt
        content: |
          -----BEGIN CERTIFICATE-----
          MIICDTCCAbOgAwIBAgIUcfMqgTUkiJGW1NI6WAdQ815DyGQwCgYIKoZIzj0EAwIw
          VzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE1pY2hpZ2FuMREwDwYDVQQHDAhCYXkg
          Q2l0eTEiMCAGA1UEAwwZemV2cmFudC1zZXJ2aWNlcy5pbnRlcm5hbDAeFw0yMzA4
          MjExODQxNTdaFw0zMzA4MTgxODQxNTdaMFcxCzAJBgNVBAYTAlVTMREwDwYDVQQI
          DAhNaWNoaWdhbjERMA8GA1UEBwwIQmF5IENpdHkxIjAgBgNVBAMMGXpldnJhbnQt
          c2VydmljZXMuaW50ZXJuYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARRvcYB
          Qlv7B+Vr5FDOHbg9BXvl7pWrkZUGxwAsOEawl4YzD/3KvOAxF8RdYnO4bSRJuU7B
          tfzbk81bnQyKDFfio10wWzAdBgNVHQ4EFgQUEpenVXHlbvZcDAtH6c/OjFieUC0w
          HwYDVR0jBBgwFoAUEpenVXHlbvZcDAtH6c/OjFieUC0wDAYDVR0TBAUwAwEB/zAL
          BgNVHQ8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIgPdHcPE/tfknCePZFNUDkL/qQ
          O1bk9g6pqOxM3bTl5HMCIQDusvA6XLr23DUCljwV8kGKLOVhwpVA9A8CAw2WbBc/
          1A==
          -----END CERTIFICATE-----
    - name: Setup Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node-exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Documentation=
          
          Wants=network.target
          After=network.target
          
          [Service]
          User=node-exporter
          
          WorkingDirectory=/opt/node-exporter
          ExecStart=/opt/node-exporter/node_exporter
          
          [Install]
          WantedBy=multi-user.target
    - name: Enable keepalived
      ansible.builtin.systemd:
        name: node-exporter
        state: started
        enabled: true
    - name: Load Certificate
      ansible.builtin.command:
        cmd: update-ca-trust
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    - name: Uncordon K8S Node
      register: cordonresult
      until: "cordonresult is not failed"
      retries: 30
      delay: 10
      become: false
      local_action: ansible.builtin.command /snap/bin/kubectl uncordon "{{ hostname }}"