apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: jenkins
spec:
  containers:
    - args:
        - "99999999"
      command:
        - sleep
      image: zevrant/zevrant-android:latest
      imagePullPolicy: Always
      name: android-emulator
      resources: { }
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
        - mountPath: /dev
          name: kvm-stuff
      workingDir: /home/jenkins/agent
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: harbor-ro
  nodeName: zevrant-03
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: { }
  serviceAccountName: jenkins
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - emptyDir: { }
      name: workspace-volume
    - name: kvm-stuff
      hostPath:
        path: /dev/

